SampleBarterApp.Web/Models/Layout/RightSideBarViewModel.cs
using SampleBarterApp.Configuration.Ui;

namespace SampleBarterApp.Web.Models.Layout
{
    public class RightSideBarViewModel
    {
        public UiThemeInfo CurrentTheme { get; set; }
    }
}

SampleBarterApp.Web/Models/Layout/SideBarNavViewModel.cs
using Abp.Application.Navigation;

namespace SampleBarterApp.Web.Models.Layout
{
    public class SideBarNavViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

SampleBarterApp.Web/Models/Layout/SideBarUserAreaViewModel.cs
using SampleBarterApp.Sessions.Dto;

namespace SampleBarterApp.Web.Models.Layout
{
    public class SideBarUserAreaViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

SampleBarterApp.Web/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using SampleBarterApp.Configuration;
using SampleBarterApp.Configuration.Ui;
using SampleBarterApp.Sessions;
using SampleBarterApp.Web.Models;
using SampleBarterApp.Web.Models.Layout;

namespace SampleBarterApp.Web.Controllers
{
    public class LayoutController : SampleBarterAppControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager,
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult SideBarNav(string activeMenu = "")
        {
            var model = new SideBarNavViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView("_SideBarNav", model);
        }

        [ChildActionOnly]
        public PartialViewResult SideBarUserArea()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return PartialView("_SideBarUserArea", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages()
            };

            return PartialView("_LanguageSelection", model);
        }

        [ChildActionOnly]
        public PartialViewResult RightSideBar()
        {
            var themeName = SettingManager.GetSettingValue(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName)
            };

            return PartialView("_RightSideBar", viewModel);
        }
    }
}

SampleBarterApp.Web/Views/Shared/Footer_Layout_PartialView.cshtml
<footer class="main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 text-center">
                <p class="mt-3">Pinaack Solutions &copy; 2018-2019</p>
            </div>

        </div>
    </div>
</footer>

SampleBarterApp.Web/Views/Shared/Layout_Header_PartialView.cshtml
@*<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand" href="#">Exchange</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
   <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="#" class="nav-link font-white">LogOut <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
        </ul>
    </div>
</nav>*@
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">Exchange</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">

            <ul class="navbar-nav ml-auto">
                <li class=" nav-item active"><a href="/HomeBuilt1/NewIndex" class="nav-link text-white">Home</a></li>
                <li class="nav-item"><a href="/HomeBuilt1/About" class="nav-link text-white">About</a></li>
                <li class="nav-item"><a href="/HomeBuilt1/SafetyTips" class="nav-link text-white">Safety Tips</a></li>
                <li class="nav-item"><a href="/HomeBuilt1/FAQ" class="nav-link text-white">FAQ</a></li>
                <li class="nav-item"><a href="/HomeBuilt1/PrivacyPolicy" class="nav-link text-white">Privacy Policy</a></li>
                <li class="nav-item"><a href="/HomeBuilt1/NewIndex" class="nav-link font-white text-white">LogOut <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                @*<li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle text-black-50" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        User Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/HomeBuilt1/Login">Login</a>
                        <a class="dropdown-item" href="/HomeBuilt1/SignUp">Register</a>
                        <a class="dropdown-item" href="/HomeBuilt1/NewDashBoard">User Dashboard</a>
                    </div>
                </li>*@
                @*<li class="nav-item"><a href="#" class="nav-link font-white">LogOut <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>*@
            </ul>
        </div>
     
    </div>
</nav>

SampleBarterApp.Web/Views/Shared/ProductDetail_PartialView.cshtml
<div class="modal fade" id="productDetails"  data-backdrop="false">
    <div class="modal-dialog modal-lg-full">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="container-fluid mb-2">
                    <div class="row">
                        <div class="col-md-12">
                            @*class="card"*@
                            <div>
                                @*class="card-body"*@
                                <div>
                                    <div class="row">
                                     
                                        <div class="col-md-12">
                                            
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <h4 class="align-center-details mb-4 mt-2"><span class="align-center-span" style="font-size:26px; background-color:white;">What I Have</span></h4>
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="form-group row">
                                                        <label for="txtproducttitle" class="col-md-3 col-form-label"><strong>Product Title</strong></label>
                                                        <div class="col-md-9">
                                                            <label type="text">Maruti Car Engine</label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label for="ddlcategory" class="col-md-3 control-label"><strong>Category</strong></label>
                                                        <div class="col-md-3">
                                                            <label type="text">Engine</label>
                                                        </div>
                                                        <label for="ddlsubcategory" class="col-md-3 "><strong>Sub Category</strong></label>
                                                        <div class="col-md-3">
                                                            <label type="text" class="text-justify">Car Engine</label>
                                                        </div>

                                                    </div>
                                               

                                                    <div class="form-group row">
                                                        <label for="txtdescription" class="col-md-3 col-form-label"><strong>Description</strong></label>
                                                        <div class="col-md-9 text-justify" >
                                                            <label type="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum tincidunt, sapien sagittis sollicitudin dapibus, risus mi euismod elit, in dictum justo lacus sit amet dui. Sed faucibus vitae nisl at dignissim. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label for="pwd" class="col-md-3"><strong>Exchange Process</strong></label>
                                                        <div class="col-md-9">
                                                                    <label type="text">Need Items</label>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <div class="col-md-2">
                                                          <img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size">

                                                        </div>
                                                        <div class="col-md-2">
                                                            <img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size">
                                                        </div>
                                                        <div class="col-md-2">
                                                            <img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size">
                                                        </div>
                                                        <div class="col-md-2">
                                                            <img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size">
                                                        </div>
                                                        <div class="col-md-2">
                                                            <img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size">
                                                        </div>
                                                    </div>
                                                </div>
                                             
                                            </div>
                                        </div>

                                        <div class="col-md-12 mt-4">
                                            <h4 class="align-center-details mb-4 mt-2"><span class="align-center-span" style="font-size:26px; background-color:white;">What I want instead</span></h4>
                                        </div>
                                      
                                                  
                                                   
                                                    <div class="col-md-12" id="Needitems">
                                                 
                                                        <p id="counter"></p>
                                                        <table class="table  table-condensed table-hover">
                                                            <tr>
                                                                <th>Product Title</th>
                                                                <th>Category</th>
                                                                <th>Sub Category</th>
                                                                <th>Description</th>
                                                                <th>Images</th>
                                                                <th></th>
                                                            </tr>
                                                            <tbody>
                                                                <tr>
                                                                 
                                                                    <td>Mark</td>
                                                                    <td>Otto</td>
                                                                    <td>Thornton</td>
                                                                    <td>
                                                                        <div class="text-justify">
                                                                            <label type="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum tincidunt, sapien sagittis sollicitudin dapibus, risus mi euismod elit, in dictum justo lacus sit amet dui. Sed faucibus vitae nisl at dignissim. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</label>
                                                                        </div>
                                                                    </td>
                                                                    <td><img src="~/customize/img/engine4.jpg" alt="..." class="img-fluid product-list-image-size"></td>
                                                                 

                                                                  
                                                                </tr>
                                                                <tr>
                                                                
                                                                    <td>Jacob</td>
                                                                    <td>Thornton</td>
                                                                    <td>Thornton</td>
                                                                    <td>
                                                                        <div class="text-justify">
                                                                            <label type="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum tincidunt, sapien sagittis sollicitudin dapibus, risus mi euismod elit, in dictum justo lacus sit amet dui. Sed faucibus vitae nisl at dignissim. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</label>
                                                                        </div>
                                                                    </td>
                                                                    <td><img src="~/customize/img/engine1.jpg" alt="..." class="img-fluid product-list-image-size"></td>
                                                                  

                                                                   
                                                                </tr>
                                                                <tr>
                                                                  
                                                                    <td>Larry</td>
                                                                    <td>the Bird</td>
                                                                    <td>Thornton</td>
                                                                    <td>
                                                                        <div class="text-justify">
                                                                            <label type="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum tincidunt, sapien sagittis sollicitudin dapibus, risus mi euismod elit, in dictum justo lacus sit amet dui. Sed faucibus vitae nisl at dignissim. Ut nec tincidunt arcu, sit amet fermentum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</label>
                                                                        </div>

                                                                    </td>
                                                                    <td><img src="~/customize/img/engine2.jpg" alt="..." class="img-fluid product-list-image-size"></td>
                                                               

                                                                   
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                           
                                      
                                    </div>


                                </div>
                            

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SampleBarterApp.Web/Views/Shared/SideBar_Layout__PartialView.cshtml
<nav class="side-navbar">

    <div class="sidebar-header d-flex align-items-center">
        <div class="avatar"><img src="/customize/vendor/img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle"></div>
        <div class="title mt-4">
            <h1 class="h6">Mark Stephen</h1>
            &nbsp;
        </div>
    </div>
    @*<button class="navbar-toggler btncollapse hide" type="button" data-toggle="collapse" data-target="#siderbar">
        <span class="navbar-toggler-icon"></span>
    </button> class="collapse navbar-collapse"*@
   
    <div  id="siderbar">
        <ul class="list-unstyled">
            <li><a class="testnvalink" href="/HomeBuilt1/NewDashBoard"> <i class="fa fa-home mr-2"></i>Dashboard</a></li>
            <li><a class="testnvalink" href="/HomeBuilt1/AddProduct"> <i class="fa fa-plus-square mr-2"></i>Add Products</a></li>
            <li><a class="testnvalink" href="/HomeBuilt1/NewMessageHistory1"> <i class="fa fa-comments-o mr-2"></i>Message History</a></li>
            @*<li><a > <i class="fa fa-bookmark mr-2"></i>Bookmark</a></li>*@
            <li><a class="testnvalink" href="/HomeBuilt1/IndentityVerification"> <i class="fa fa-check-circle mr-2"></i>Indentity Verification</a></li>
            <li><a class="testnvalink" href="/HomeBuilt1/UserProfile"> <i class="fa fa-user mr-2"></i>My Profile</a></li>
            <li><a class="testnvalink" href="/HomeBuilt1/Notification"> <i class="fa fa-bell mr-2"></i>User Notification</a></li>
        </ul>
    </div>
</nav>

SampleBarterApp.Web/Views/Shared/UserHomeHeaderFooter_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/customize/css/mycss.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/customize/js/Myjs.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Sanchez" rel="stylesheet">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&lang=en">
</head>
<body class="fontweb">
    <section id="header">
        @Html.Partial("UserHomeNavbar_PartialView")
    </section>
   
    <div class="container-fluid mt-5">
        <div class="row">
           
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>

    </div>
    <section id="footer">
        @Html.Partial("UserHomeFooterPartialView")
    </section>
</body>
</html>

SampleBarterApp.Web/Views/Shared/UserHomeLayoutWithoutSlider _LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/customize/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/customize/css/mycss.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/customize/js/bootstrap.js"></script>
    <script src="~/customize/js/Myjs.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/customize/css/xzoom.css" rel="stylesheet" />
    <script src="~/customize/js/xzoom.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Sanchez" rel="stylesheet">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&lang=en">

</head>
<body class="fontweb">
    <section id="header">
        @Html.Partial("UserHomeNavbar_PartialView")
    </section>
  
    <section id="SearchBar" class="mt-5 pt-3">
        <div class="container-fluid" style="background-color:#f3f3f0">
            <section class="align-content-center">@Html.Partial("UserHomeSearchbar_PartialView")</section>
        </div>
    </section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>

    </div>
    <section id="footer">
        @Html.Partial("UserHomeFooterPartialView")
    </section>
    <script src="~/customize/js/setup.js"></script>

    <script>
        $(document).ready(function () {
            $('#loginbtn').click(function () {
                $("#loginmodal").modal('show');
            })
            $('#signuppopupbtn').click(function () {
                $("#SignUpmodal").modal('show');
            })
            $('#loginpopupbtn').click(function () {
                $("#loginmodal").modal('show');
            })
        });
    </script>
</body>
</html>

SampleBarterApp.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Configuration
@using Abp.Timing
@using SampleBarterApp
@using SampleBarterApp.Configuration
@using Abp.Dependency
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Mvc.Extensions
@{
    Layout = null;
    SetAntiForgeryCookie();
    var uiTheme = SettingManager.GetSettingValue(AppSettingNames.UiTheme);
    AlertList alerts = null;
    IocManager.Instance.Using<IAlertManager>(alertManager => alerts = alertManager.Alerts);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>SampleBarterApp</title>

    @Styles.Render("~/Bundles/vendor/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>
</head>
<body class="@("theme-" + uiTheme)">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-cubes"></i> SampleBarterApp</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- Call Search -->
                    <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                    <!-- #END# Call Search -->
                    @Html.Action("LanguageSelection", "Layout")

                    <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <aside id="leftsidebar" class="sidebar">

            @Html.Action("SideBarUserArea", "Layout")
            @Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })

            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; @DateTime.Now.Year <a href="javascript:void(0);">SampleBarterApp</a>.
                </div>
                <div class="version">
                    <b>Version </b> @AppVersionHelper.Version [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
                </div>
            </div>
            <!-- #Footer -->
        </aside>

        @Html.Action("RightSideBar", "Layout")

    </section>

    <section class="content">
        <div class="container-fluid">
            @if (alerts.Any())
            {
                <div id="AbpPageAlerts">
                    @foreach (var alertMessage in alerts)
                    {
                        <div class="alert alert-@alertMessage.Type.ToString().ToLower() @(alertMessage.Dismissible ? "alert-dismisable" : "")" role="alert">
                            <h4 class="alert-heading">
                                @alertMessage.Title
                                @if (alertMessage.Dismissible)
                                {
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                }
                            </h4>
                            <p>@alertMessage.Text</p>
                        </div>
                    }
                </div>
            }

            @RenderBody()
        </div>
    </section>

    @Scripts.Render("~/Bundles/vendor/js/bottom")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>